[project]
name = "templater"
version = "0.1.0"
description = "Templater for dotfiles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
    "ty>=0.0.16",
    "uv-upsync>=2.1.0",
]
